import type {
  ICompany,
  IEmployee,
  IDocument,
  ITask,
  ILiability,
  IZaadExpense,
  IUser,
  IIndividual,
  IRecord,
  IInvoice,
  IUserActivity,
} from "@/types";

export const generateId = () => Math.random().toString(36).substr(2, 9);

export const generateCompanies = (): ICompany[] => [
  {
    _id: "comp_1",
    name: "Al Waha Tech Solutions",
    licenseNo: "CN-1234567",
    companyType: "LLC",
    emirates: "Dubai",
    phone1: "+971501234567",
    phone2: "+971501234568",
    email: "contact@alwaha.ae",
    isMainland: "mainland",
    transactionNo: "TXN-2024-001",
    remarks: "Established tech company with strong IT portfolio",
    published: true,
    createdAt: new Date("2022-03-15").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_2",
    name: "Skyline Construction",
    licenseNo: "CN-7654321",
    companyType: "Sole Proprietorship",
    emirates: "Abu Dhabi",
    phone1: "+971509876543",
    phone2: "+971509876544",
    email: "info@skyline.ae",
    isMainland: "mainland",
    transactionNo: "TXN-2024-002",
    remarks: "Construction company specializing in residential projects",
    published: true,
    createdAt: new Date("2021-08-10").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_3",
    name: "Global Trade FZCO",
    licenseNo: "FZ-112233",
    companyType: "Freezone",
    emirates: "Dubai",
    phone1: "+971523344556",
    phone2: "+971523344557",
    email: "admin@globaltrade.ae",
    isMainland: "freezone",
    transactionNo: "TXN-2024-003",
    remarks: "Import/Export trading company in Jebel Ali Free Zone",
    published: true,
    createdAt: new Date("2020-02-28").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_4",
    name: "Emirates Healthcare Services",
    licenseNo: "CN-2345678",
    companyType: "LLC",
    emirates: "Sharjah",
    phone1: "+971506789012",
    phone2: "+971506789013",
    email: "info@emirateshealthcare.ae",
    isMainland: "mainland",
    transactionNo: "TXN-2024-004",
    remarks: "Licensed healthcare provider with medical facilities",
    published: true,
    createdAt: new Date("2021-01-10").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_5",
    name: "Desert Digital Marketing",
    licenseNo: "FZ-223344",
    companyType: "Freezone",
    emirates: "Dubai",
    phone1: "+971507890123",
    phone2: "+971507890124",
    email: "hello@desertdigital.ae",
    isMainland: "freezone",
    transactionNo: "TXN-2024-005",
    remarks: "Digital marketing agency in Dubai Media City",
    published: true,
    createdAt: new Date("2020-09-01").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_6",
    name: "Pearl Hospitality Group",
    licenseNo: "CN-3456789",
    companyType: "LLC",
    emirates: "Abu Dhabi",
    phone1: "+971508901234",
    phone2: "+971508901235",
    email: "contact@pearlhospitality.ae",
    isMainland: "mainland",
    transactionNo: "TXN-2024-006",
    remarks: "Hotel and resort management company",
    published: true,
    createdAt: new Date("2019-06-01").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_7",
    name: "Oasis Logistics FZCO",
    licenseNo: "FZ-334455",
    companyType: "Freezone",
    emirates: "Dubai",
    phone1: "+971509012345",
    phone2: "+971509012346",
    email: "ops@oasislogistics.ae",
    isMainland: "freezone",
    transactionNo: "TXN-2024-007",
    remarks: "Logistics and warehousing in Jebel Ali Free Zone",
    published: true,
    createdAt: new Date("2021-03-10").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_8",
    name: "Falcon Engineering",
    licenseNo: "CN-4567890",
    companyType: "Sole Proprietorship",
    emirates: "Ajman",
    phone1: "+971500123456",
    phone2: "+971500123457",
    email: "info@falconeng.ae",
    isMainland: "mainland",
    transactionNo: "TXN-2024-008",
    remarks: "Civil and mechanical engineering services",
    published: true,
    createdAt: new Date("2020-11-15").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_9",
    name: "Dune Finance Consultancy",
    licenseNo: "FZ-445566",
    companyType: "Freezone",
    emirates: "Dubai",
    phone1: "+971501234678",
    phone2: "+971501234679",
    email: "contact@dunefinance.ae",
    isMainland: "freezone",
    transactionNo: "TXN-2024-009",
    remarks: "Financial advisory and investment consulting",
    published: true,
    createdAt: new Date("2021-01-20").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_10",
    name: "Gulf Auto Trading",
    licenseNo: "CN-5678901",
    companyType: "LLC",
    emirates: "Dubai",
    phone1: "+971502345789",
    phone2: "+971502345790",
    email: "sales@gulfauto.ae",
    isMainland: "mainland",
    transactionNo: "TXN-2024-010",
    remarks: "Automotive dealer and rental services",
    published: true,
    createdAt: new Date("2019-05-12").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_11",
    name: "Platinum Real Estate",
    licenseNo: "CN-6789012",
    companyType: "LLC",
    emirates: "Abu Dhabi",
    phone1: "+971503456890",
    phone2: "+971503456891",
    email: "info@platinumrealestate.ae",
    isMainland: "mainland",
    transactionNo: "TXN-2024-011",
    remarks: "Premium real estate agency and property management",
    published: true,
    createdAt: new Date("2018-08-01").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_12",
    name: "Summit Food Industries",
    licenseNo: "CN-7890123",
    companyType: "LLC",
    emirates: "Sharjah",
    phone1: "+971504567901",
    phone2: "+971504567902",
    email: "admin@summitfood.ae",
    isMainland: "mainland",
    transactionNo: "TXN-2024-012",
    remarks: "Food manufacturing and distribution company",
    published: true,
    createdAt: new Date("2020-02-10").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_13",
    name: "Bright Future Education",
    licenseNo: "FZ-556677",
    companyType: "Freezone",
    emirates: "Dubai",
    phone1: "+971505678012",
    phone2: "+971505678013",
    email: "info@brightfuture.ae",
    isMainland: "freezone",
    transactionNo: "TXN-2024-013",
    remarks: "Educational institution and training center",
    published: true,
    createdAt: new Date("2019-09-01").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_14",
    name: "Zenith IT Solutions",
    licenseNo: "CN-8901234",
    companyType: "Sole Proprietorship",
    emirates: "Dubai",
    phone1: "+971506789123",
    phone2: "+971506789124",
    email: "support@zenithit.ae",
    isMainland: "mainland",
    transactionNo: "TXN-2024-014",
    remarks: "IT services, software development and infrastructure solutions",
    published: true,
    createdAt: new Date("2019-04-01").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_15",
    name: "Arabian Textiles FZCO",
    licenseNo: "FZ-667788",
    companyType: "Freezone",
    emirates: "Sharjah",
    phone1: "+971507890234",
    phone2: "+971507890235",
    email: "contact@arabiantextiles.ae",
    isMainland: "freezone",
    transactionNo: "TXN-2024-015",
    remarks: "Textile manufacturing and export in Hamriyah Free Zone",
    published: true,
    createdAt: new Date("2019-10-20").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_16",
    name: "Vista Property Management",
    licenseNo: "CN-9012345",
    companyType: "LLC",
    emirates: "Abu Dhabi",
    phone1: "+971508901345",
    phone2: "+971508901346",
    email: "management@vistaproperty.ae",
    isMainland: "mainland",
    transactionNo: "TXN-2024-016",
    remarks: "Residential and commercial property management services",
    published: true,
    createdAt: new Date("2020-12-01").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_17",
    name: "Crystal Events & Catering",
    licenseNo: "CN-0123456",
    companyType: "LLC",
    emirates: "Dubai",
    phone1: "+971509012456",
    phone2: "+971509012457",
    email: "events@crystalcatering.ae",
    isMainland: "mainland",
    transactionNo: "TXN-2024-017",
    remarks: "Event planning and catering services provider",
    published: true,
    createdAt: new Date("2021-03-15").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "comp_18",
    name: "Mirage Trading FZCO",
    licenseNo: "FZ-778899",
    companyType: "Freezone",
    emirates: "Dubai",
    phone1: "+971500123567",
    phone2: "+971500123568",
    email: "trade@miragetrading.ae",
    isMainland: "freezone",
    transactionNo: "TXN-2024-018",
    remarks: "General trading and wholesale distribution in JAFZ",
    published: true,
    createdAt: new Date("2021-05-10").toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const generateEmployees = (): IEmployee[] => [
  {
    _id: "emp_1",
    name: "John Doe",
    company: "comp_1",
    isActive: true,
    designation: "General Manager",
    nationality: "USA",
    phone1: "+971551234567",
    email: "john@alwaha.ae",
    emiratesId: "784-1985-1234567-1",
    remarks: "Leads company operations, strong team management",
    published: true,
    createdAt: new Date("2021-03-10").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_2",
    name: "Jane Smith",
    company: "comp_1",
    isActive: true,
    designation: "Accountant",
    nationality: "UK",
    phone1: "+971559876543",
    email: "jane@alwaha.ae",
    emiratesId: "784-1990-7654321-2",
    remarks: "Manages financial records and reporting",
    published: true,
    createdAt: new Date("2021-06-15").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_3",
    name: "Ahmed Ali",
    company: "comp_2",
    isActive: false,
    designation: "PRO",
    nationality: "Egypt",
    phone1: "+971501112233",
    email: "ahmed@skyline.ae",
    emiratesId: "784-1988-1122334-3",
    remarks: "Handles government relations (inactive as of Dec 2024)",
    published: true,
    createdAt: new Date("2020-01-20").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_4",
    name: "Sarah Johnson",
    company: "comp_4",
    isActive: true,
    designation: "HR Manager",
    nationality: "Canada",
    phone1: "+971552234567",
    email: "sarah@emirateshealthcare.ae",
    emiratesId: "784-1992-2234567-4",
    remarks: "Oversees recruitment and employee relations",
    published: true,
    createdAt: new Date("2022-02-01").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_5",
    name: "Mohammed Hassan",
    company: "comp_5",
    isActive: true,
    designation: "Marketing Director",
    nationality: "Jordan",
    phone1: "+971553345678",
    email: "mohammed@desertdigital.ae",
    emiratesId: "784-1987-3345678-5",
    remarks: "Drives digital marketing campaigns",
    published: true,
    createdAt: new Date("2021-09-05").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_6",
    name: "Emily Chen",
    company: "comp_6",
    isActive: true,
    designation: "Operations Manager",
    nationality: "Singapore",
    phone1: "+971554456789",
    email: "emily@pearlhospitality.ae",
    emiratesId: "784-1991-4456789-6",
    remarks: "Manages daily operational activities",
    published: true,
    createdAt: new Date("2022-05-12").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_7",
    name: "Rashid Al Maktoum",
    company: "comp_7",
    isActive: true,
    designation: "Logistics Coordinator",
    nationality: "UAE",
    phone1: "+971555567890",
    email: "rashid@oasislogistics.ae",
    emiratesId: "784-1989-5567890-7",
    remarks: "Coordinates shipping and delivery operations",
    published: true,
    createdAt: new Date("2021-11-08").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_8",
    name: "Priya Patel",
    company: "comp_8",
    isActive: true,
    designation: "Senior Engineer",
    nationality: "India",
    phone1: "+971556678901",
    email: "priya@falconeng.ae",
    emiratesId: "784-1993-6678901-8",
    remarks: "Leads engineering projects and team",
    published: true,
    createdAt: new Date("2020-07-22").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_9",
    name: "David Williams",
    company: "comp_9",
    isActive: true,
    designation: "Financial Advisor",
    nationality: "Australia",
    phone1: "+971557789012",
    email: "david@dunefinance.ae",
    emiratesId: "784-1986-7789012-9",
    remarks: "Provides investment and financial planning services",
    published: true,
    createdAt: new Date("2022-01-14").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_10",
    name: "Fatima Al Zarooni",
    company: "comp_10",
    isActive: true,
    designation: "Sales Manager",
    nationality: "UAE",
    phone1: "+971558890123",
    email: "fatima@gulfauto.ae",
    emiratesId: "784-1990-8890123-0",
    remarks: "Manages sales team and client relationships",
    published: true,
    createdAt: new Date("2021-04-09").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_11",
    name: "Carlos Rodriguez",
    company: "comp_11",
    isActive: true,
    designation: "Real Estate Broker",
    nationality: "Spain",
    phone1: "+971559901234",
    email: "carlos@platinumrealestate.ae",
    emiratesId: "784-1988-9901234-1",
    remarks: "Specializes in commercial and residential properties",
    published: true,
    createdAt: new Date("2022-08-18").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_12",
    name: "Aisha Mohammed",
    company: "comp_12",
    isActive: true,
    designation: "Production Supervisor",
    nationality: "Sudan",
    phone1: "+971550012345",
    email: "aisha@summitfood.ae",
    emiratesId: "784-1991-0012345-2",
    remarks: "Oversees production quality and efficiency",
    published: true,
    createdAt: new Date("2020-10-25").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_13",
    name: "Thomas Anderson",
    company: "comp_13",
    isActive: true,
    designation: "Academic Director",
    nationality: "USA",
    phone1: "+971551123456",
    email: "thomas@brightfuture.ae",
    emiratesId: "784-1984-1123456-3",
    remarks: "Directs curriculum and academic programs",
    published: true,
    createdAt: new Date("2019-09-03").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_14",
    name: "Yuki Tanaka",
    company: "comp_14",
    isActive: true,
    designation: "IT Specialist",
    nationality: "Japan",
    phone1: "+971552234567",
    email: "yuki@zenithit.ae",
    emiratesId: "784-1994-2234567-4",
    remarks: "Manages IT infrastructure and support",
    published: true,
    createdAt: new Date("2022-11-07").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_15",
    name: "Omar Khalid",
    company: "comp_15",
    isActive: true,
    designation: "Supply Chain Manager",
    nationality: "Pakistan",
    phone1: "+971553345678",
    email: "omar@arabiantextiles.ae",
    emiratesId: "784-1989-3345678-5",
    remarks: "Manages procurement and supply chain",
    published: true,
    createdAt: new Date("2021-12-20").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_16",
    name: "Lisa Brown",
    company: "comp_16",
    isActive: true,
    designation: "Property Manager",
    nationality: "UK",
    phone1: "+971554456789",
    email: "lisa@vistaproperty.ae",
    emiratesId: "784-1992-4456789-6",
    remarks: "Manages properties and tenant relations",
    published: true,
    createdAt: new Date("2022-03-16").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_17",
    name: "Hassan Ibrahim",
    company: "comp_17",
    isActive: false,
    designation: "Executive Chef",
    nationality: "Lebanon",
    phone1: "+971555567890",
    email: "hassan@crystalcatering.ae",
    emiratesId: "784-1987-5567890-7",
    remarks: "Head chef (contract ended Nov 2024)",
    published: true,
    createdAt: new Date("2021-01-11").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_18",
    name: "Maria Garcia",
    company: "comp_18",
    isActive: true,
    designation: "Import/Export Manager",
    nationality: "Philippines",
    phone1: "+971556678901",
    email: "maria@miragetrading.ae",
    emiratesId: "784-1993-6678901-8",
    remarks: "Handles international trade operations",
    published: true,
    createdAt: new Date("2022-06-30").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_19",
    name: "Ali Saeed",
    company: "comp_3",
    isActive: true,
    designation: "Business Development",
    nationality: "UAE",
    phone1: "+971557789012",
    email: "ali@globaltrade.ae",
    emiratesId: "784-1990-7789012-9",
    remarks: "Identifies and develops new business opportunities",
    published: true,
    createdAt: new Date("2021-08-25").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "emp_20",
    name: "Nina Petrov",
    company: "comp_1",
    isActive: true,
    designation: "Software Developer",
    nationality: "Russia",
    phone1: "+971558890123",
    email: "nina@alwaha.ae",
    emiratesId: "784-1995-8890123-0",
    remarks: "Develops and maintains software solutions",
    published: true,
    createdAt: new Date("2023-02-14").toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const generateDocuments = (): IDocument[] => [
  {
    _id: "doc_1",
    company: "comp_1",
    name: "Trade License",
    type: "License",
    expiryDate: "2025-01-01",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_2",
    employee: "emp_1",
    name: "Labor Card",
    type: "Labor Card",
    expiryDate: "2025-06-01",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_3",
    company: "comp_2",
    name: "Trade License",
    type: "License",
    expiryDate: "2026-03-15",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_4",
    employee: "emp_2",
    name: "Visa",
    type: "Visa",
    expiryDate: "2026-02-20",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_5",
    company: "comp_3",
    name: "Free Zone License",
    type: "License",
    expiryDate: "2025-12-31",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_6",
    employee: "emp_4",
    name: "Emirates ID",
    type: "Emirates ID",
    expiryDate: "2027-08-10",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_7",
    employee: "emp_5",
    name: "Labor Card",
    type: "Labor Card",
    expiryDate: "2025-11-22",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_8",
    company: "comp_4",
    name: "Health License",
    type: "License",
    expiryDate: "2026-05-30",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_9",
    employee: "emp_6",
    name: "Passport",
    type: "Passport",
    expiryDate: "2028-04-15",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_10",
    company: "comp_5",
    name: "Trade License",
    type: "License",
    expiryDate: "2025-09-20",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_11",
    employee: "emp_7",
    name: "Visa",
    type: "Visa",
    expiryDate: "2026-07-18",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_12",
    employee: "emp_8",
    name: "Emirates ID",
    type: "Emirates ID",
    expiryDate: "2027-01-25",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_13",
    company: "comp_6",
    name: "Tourism License",
    type: "License",
    expiryDate: "2026-06-12",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_14",
    employee: "emp_9",
    name: "Labor Card",
    type: "Labor Card",
    expiryDate: "2025-10-05",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_15",
    company: "comp_7",
    name: "Free Zone License",
    type: "License",
    expiryDate: "2025-08-30",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_16",
    employee: "emp_10",
    name: "Passport",
    type: "Passport",
    expiryDate: "2029-03-14",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_17",
    employee: "emp_11",
    name: "Visa",
    type: "Visa",
    expiryDate: "2026-12-08",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "doc_18",
    company: "comp_8",
    name: "Trade License",
    type: "License",
    expiryDate: "2026-04-22",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const generateTasks = (): ITask[] => [
  {
    _id: "task_1",
    title: "Renew Trade License",
    description: "Contact PRO for renewal",
    createdBy: "user_1",
    status: "pending",
    priority: "high",
    dueDate: "2024-12-31",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "task_2",
    title: "Submit Quarterly Tax Report",
    description: "Prepare and submit Q4 tax documentation",
    createdBy: "user_2",
    status: "in-progress",
    priority: "high",
    dueDate: "2026-01-15",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "task_3",
    title: "Employee Visa Renewal",
    description: "Renew visa for 5 employees expiring this month",
    createdBy: "user_1",
    status: "pending",
    priority: "medium",
    dueDate: "2026-01-25",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "task_4",
    title: "Update Company Agreements",
    description: "Review and update partnership agreements",
    createdBy: "user_1",
    status: "completed",
    priority: "low",
    dueDate: "2025-12-20",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "task_5",
    title: "Schedule Board Meeting",
    description: "Organize monthly board meeting for January",
    createdBy: "user_2",
    status: "in-progress",
    priority: "medium",
    dueDate: "2026-01-18",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "task_6",
    title: "Insurance Policy Review",
    description: "Review all company insurance policies",
    createdBy: "user_1",
    status: "pending",
    priority: "medium",
    dueDate: "2026-02-01",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "task_7",
    title: "Payroll Processing",
    description: "Process monthly payroll for all employees",
    createdBy: "user_2",
    status: "completed",
    priority: "high",
    dueDate: "2026-01-05",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "task_8",
    title: "Update Website Content",
    description: "Add new services section to company website",
    createdBy: "user_2",
    status: "in-progress",
    priority: "low",
    dueDate: "2026-01-30",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "task_9",
    title: "Client Feedback Survey",
    description: "Send quarterly satisfaction survey to all clients",
    createdBy: "user_1",
    status: "pending",
    priority: "low",
    dueDate: "2026-01-22",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "task_10",
    title: "Inventory Audit",
    description: "Conduct full warehouse inventory check",
    createdBy: "user_2",
    status: "pending",
    priority: "medium",
    dueDate: "2026-01-28",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "task_11",
    title: "Security System Upgrade",
    description: "Install new security cameras in office",
    createdBy: "user_1",
    status: "in-progress",
    priority: "high",
    dueDate: "2026-01-20",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "task_12",
    title: "Staff Training Session",
    description: "Organize safety and compliance training",
    createdBy: "user_2",
    status: "pending",
    priority: "medium",
    dueDate: "2026-02-05",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "task_13",
    title: "Contract Negotiation",
    description: "Negotiate terms with new supplier",
    createdBy: "user_1",
    status: "in-progress",
    priority: "high",
    dueDate: "2026-01-17",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "task_14",
    title: "Update Emergency Contacts",
    description: "Verify and update all employee emergency contacts",
    createdBy: "user_2",
    status: "completed",
    priority: "low",
    dueDate: "2025-12-28",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "task_15",
    title: "Prepare Annual Report",
    description: "Compile 2025 annual business report",
    createdBy: "user_1",
    status: "in-progress",
    priority: "high",
    dueDate: "2026-01-31",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "task_16",
    title: "Office Maintenance Check",
    description: "Schedule HVAC and electrical systems inspection",
    createdBy: "user_2",
    status: "pending",
    priority: "low",
    dueDate: "2026-02-10",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "task_17",
    title: "Marketing Campaign Launch",
    description: "Launch Q1 2026 marketing campaign",
    createdBy: "user_1",
    status: "pending",
    priority: "medium",
    dueDate: "2026-01-25",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const generateLiabilities = (): ILiability[] => [
  {
    _id: "lib_1",
    company: "comp_1",
    type: "payable",
    amount: 15000,
    paidAmount: 5000,
    description: "Office Renovation Loan",
    status: "partial",
    dueDate: "2023-12-01",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_2",
    company: "comp_2",
    type: "receivable",
    amount: 8500,
    paidAmount: 0,
    description: "Consulting Services",
    status: "pending",
    dueDate: "2024-02-15",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_3",
    individual: "ind_1",
    type: "loan",
    amount: 50000,
    paidAmount: 50000,
    description: "Personal Loan Repayment",
    status: "paid",
    dueDate: "2023-10-10",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_4",
    company: "comp_3",
    type: "payable",
    amount: 25000,
    paidAmount: 10000,
    description: "Equipment Purchase",
    status: "partial",
    dueDate: "2026-03-20",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_5",
    company: "comp_4",
    type: "receivable",
    amount: 12000,
    paidAmount: 0,
    description: "Medical Services Invoice",
    status: "pending",
    dueDate: "2026-02-10",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_6",
    company: "comp_5",
    type: "loan",
    amount: 75000,
    paidAmount: 30000,
    description: "Business Expansion Loan",
    status: "partial",
    dueDate: "2026-12-31",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_7",
    individual: "ind_2",
    type: "payable",
    amount: 3500,
    paidAmount: 3500,
    description: "Car Loan Final Payment",
    status: "paid",
    dueDate: "2025-11-15",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_8",
    company: "comp_6",
    type: "receivable",
    amount: 18000,
    paidAmount: 6000,
    description: "Hotel Booking Services",
    status: "partial",
    dueDate: "2026-01-25",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_9",
    company: "comp_7",
    type: "payable",
    amount: 45000,
    paidAmount: 0,
    description: "Logistics Software License",
    status: "pending",
    dueDate: "2026-02-28",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_10",
    company: "comp_8",
    type: "receivable",
    amount: 22000,
    paidAmount: 22000,
    description: "Engineering Project Payment",
    status: "paid",
    dueDate: "2025-12-10",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_11",
    individual: "ind_3",
    type: "loan",
    amount: 35000,
    paidAmount: 15000,
    description: "Property Investment Loan",
    status: "partial",
    dueDate: "2026-06-30",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_12",
    company: "comp_9",
    type: "receivable",
    amount: 28000,
    paidAmount: 0,
    description: "Financial Advisory Services",
    status: "pending",
    dueDate: "2026-01-31",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_13",
    company: "comp_10",
    type: "payable",
    amount: 55000,
    paidAmount: 20000,
    description: "Vehicle Fleet Purchase",
    status: "partial",
    dueDate: "2026-04-15",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_14",
    company: "comp_11",
    type: "receivable",
    amount: 95000,
    paidAmount: 50000,
    description: "Property Sale Commission",
    status: "partial",
    dueDate: "2026-03-10",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_15",
    individual: "ind_4",
    type: "payable",
    amount: 8000,
    paidAmount: 0,
    description: "Medical Treatment Expense",
    status: "pending",
    dueDate: "2026-02-05",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_16",
    company: "comp_12",
    type: "loan",
    amount: 120000,
    paidAmount: 40000,
    description: "Factory Equipment Financing",
    status: "partial",
    dueDate: "2027-01-15",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_17",
    company: "comp_13",
    type: "receivable",
    amount: 16500,
    paidAmount: 16500,
    description: "Education Course Fees",
    status: "paid",
    dueDate: "2025-12-20",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "lib_18",
    company: "comp_14",
    type: "payable",
    amount: 32000,
    paidAmount: 8000,
    description: "Server Infrastructure Setup",
    status: "partial",
    dueDate: "2026-05-01",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const generateExpenses = (): IZaadExpense[] => [
  {
    _id: "exp_1",
    title: "Monthly Office Rent",
    amount: 8500,
    category: "Rent",
    date: "2024-01-01",
    description: "January Rent",
    paymentMethod: "Bank Transfer",
    status: "paid",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_2",
    title: "DEWA Bill",
    amount: 1200,
    category: "Utilities",
    date: "2024-01-05",
    description: "Electricity and Water",
    paymentMethod: "Bank Transfer",
    status: "paid",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_3",
    title: "Internet & Phone Services",
    amount: 850,
    category: "Utilities",
    date: "2024-01-03",
    description: "Monthly telecommunications",
    paymentMethod: "Bank Transfer",
    status: "paid",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_4",
    title: "Office Supplies",
    amount: 450,
    category: "Office Expenses",
    date: "2024-01-07",
    description: "Stationery and printing materials",
    paymentMethod: "Cash",
    status: "paid",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_5",
    title: "Employee Salaries",
    amount: 125000,
    category: "Payroll",
    date: "2024-01-01",
    description: "Monthly payroll for December",
    paymentMethod: "Bank Transfer",
    status: "paid",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_6",
    title: "Marketing Campaign",
    amount: 5500,
    category: "Marketing",
    date: "2024-01-08",
    description: "Social media advertising",
    paymentMethod: "Bank Transfer",
    status: "paid",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_7",
    title: "Software Subscriptions",
    amount: 2200,
    category: "Software",
    date: "2024-01-02",
    description: "Annual licenses renewal",
    paymentMethod: "Bank Transfer",
    status: "paid",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_8",
    title: "Vehicle Fuel",
    amount: 950,
    category: "Transportation",
    date: "2024-01-06",
    description: "Company vehicles fuel",
    paymentMethod: "Bank Transfer",
    status: "paid",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_9",
    title: "Insurance Premium",
    amount: 3800,
    category: "Insurance",
    date: "2024-01-04",
    description: "Quarterly business insurance",
    paymentMethod: "Bank Transfer",
    status: "pending",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_10",
    title: "Professional Fees",
    amount: 4500,
    category: "Legal",
    date: "2024-01-09",
    description: "Legal consultation services",
    paymentMethod: "Bank Transfer",
    status: "paid",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_11",
    title: "Equipment Maintenance",
    amount: 1800,
    category: "Maintenance",
    date: "2024-01-05",
    description: "Office equipment servicing",
    paymentMethod: "Cash",
    status: "paid",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_12",
    title: "Training Workshop",
    amount: 6500,
    category: "Training",
    date: "2024-01-10",
    description: "Employee skills development",
    paymentMethod: "Bank Transfer",
    status: "pending",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_13",
    title: "Travel Expenses",
    amount: 8200,
    category: "Travel",
    date: "2024-01-08",
    description: "Business trip to Abu Dhabi",
    paymentMethod: "Bank Transfer",
    status: "paid",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_14",
    title: "Cleaning Services",
    amount: 650,
    category: "Maintenance",
    date: "2024-01-03",
    description: "Monthly office cleaning",
    paymentMethod: "Cash",
    status: "paid",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_15",
    title: "Client Entertainment",
    amount: 1500,
    category: "Entertainment",
    date: "2024-01-07",
    description: "Business dinner with clients",
    paymentMethod: "Bank Transfer",
    status: "paid",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_16",
    title: "Bank Charges",
    amount: 250,
    category: "Banking",
    date: "2024-01-02",
    description: "Monthly account fees",
    paymentMethod: "Bank Transfer",
    status: "paid",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_17",
    title: "Security Services",
    amount: 2500,
    category: "Security",
    date: "2024-01-01",
    description: "Monthly security guard service",
    paymentMethod: "Bank Transfer",
    status: "paid",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "exp_18",
    title: "Parking Fees",
    amount: 800,
    category: "Transportation",
    date: "2024-01-04",
    description: "Monthly parking charges",
    paymentMethod: "Cash",
    status: "paid",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const generateUsers = (): IUser[] => [
  {
    _id: "user_1",
    name: "Admin User",
    email: "admin@zaad.ae",
    role: "partner",
    status: "active",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "user_2",
    name: "Sarah Connor",
    email: "sarah@zaad.ae",
    role: "employee",
    status: "active",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "user_3",
    name: "Michael Chen",
    email: "michael@zaad.ae",
    role: "employee",
    status: "active",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "user_4",
    name: "Emma Wilson",
    email: "emma@zaad.ae",
    role: "partner",
    status: "active",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "user_5",
    name: "Omar Abdullah",
    email: "omar@zaad.ae",
    role: "employee",
    status: "active",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "user_6",
    name: "Linda Martinez",
    email: "linda@zaad.ae",
    role: "employee",
    status: "inactive",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "user_7",
    name: "James Taylor",
    email: "james@zaad.ae",
    role: "partner",
    status: "active",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "user_8",
    name: "Aisha Khan",
    email: "aisha@zaad.ae",
    role: "employee",
    status: "active",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "user_9",
    name: "Robert Brown",
    email: "robert@zaad.ae",
    role: "employee",
    status: "active",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "user_10",
    name: "Sophia Lee",
    email: "sophia@zaad.ae",
    role: "employee",
    status: "active",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "user_11",
    name: "Ahmed Khalil",
    email: "ahmed.k@zaad.ae",
    role: "partner",
    status: "active",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "user_12",
    name: "Jessica White",
    email: "jessica@zaad.ae",
    role: "employee",
    status: "active",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "user_13",
    name: "Youssef Ibrahim",
    email: "youssef@zaad.ae",
    role: "employee",
    status: "inactive",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "user_14",
    name: "Rachel Green",
    email: "rachel@zaad.ae",
    role: "employee",
    status: "active",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "user_15",
    name: "Mohammed Rashid",
    email: "mohammed@zaad.ae",
    role: "partner",
    status: "active",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const generateIndividuals = (): IIndividual[] => [
  {
    _id: "ind_1",
    name: "Ali Hassan",
    nationality: "UAE",
    passportNo: "N123456",
    phone: "+971501234567",
    email: "ali@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "ind_2",
    name: "Fatima Al Mansoori",
    nationality: "UAE",
    passportNo: "N765432",
    phone: "+971509876543",
    email: "fatima@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "ind_3",
    name: "Rajesh Kumar",
    nationality: "India",
    passportNo: "J8765432",
    phone: "+971502345678",
    email: "rajesh@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "ind_4",
    name: "Maria Santos",
    nationality: "Philippines",
    passportNo: "P3456789",
    phone: "+971503456789",
    email: "maria@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "ind_5",
    name: "Ahmed Yousef",
    nationality: "Egypt",
    passportNo: "A9876543",
    phone: "+971504567890",
    email: "ahmed@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "ind_6",
    name: "Jennifer Adams",
    nationality: "USA",
    passportNo: "US234567",
    phone: "+971505678901",
    email: "jennifer@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "ind_7",
    name: "Hassan Mahmoud",
    nationality: "Jordan",
    passportNo: "JO345678",
    phone: "+971506789012",
    email: "hassan@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "ind_8",
    name: "Leila Ahmad",
    nationality: "Lebanon",
    passportNo: "LB456789",
    phone: "+971507890123",
    email: "leila@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "ind_9",
    name: "David Thompson",
    nationality: "UK",
    passportNo: "GB567890",
    phone: "+971508901234",
    email: "david@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "ind_10",
    name: "Noura Al Shamsi",
    nationality: "UAE",
    passportNo: "N678901",
    phone: "+971509012345",
    email: "noura@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "ind_11",
    name: "Sanjay Patel",
    nationality: "India",
    passportNo: "J7890123",
    phone: "+971500123456",
    email: "sanjay@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "ind_12",
    name: "Samantha Lee",
    nationality: "Singapore",
    passportNo: "SG890123",
    phone: "+971501234678",
    email: "samantha@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "ind_13",
    name: "Khaled Nasser",
    nationality: "Saudi Arabia",
    passportNo: "SA901234",
    phone: "+971502345789",
    email: "khaled@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "ind_14",
    name: "Anna Kowalski",
    nationality: "Poland",
    passportNo: "PL012345",
    phone: "+971503456890",
    email: "anna@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "ind_15",
    name: "Mohammed Saleh",
    nationality: "Yemen",
    passportNo: "YE123456",
    phone: "+971504567901",
    email: "mohammed.s@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "ind_16",
    name: "Chen Wei",
    nationality: "China",
    passportNo: "CN234567",
    phone: "+971505678012",
    email: "chen@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "ind_17",
    name: "Sara Al Falasi",
    nationality: "UAE",
    passportNo: "N345678",
    phone: "+971506789123",
    email: "sara@example.com",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const generateRecords = (): IRecord[] => [
  {
    _id: "rec_1",
    type: "income",
    category: "Service",
    amount: 5000,
    date: "2024-01-02",
    method: "cash",
    company: "comp_1",
    particular: "Consulting Fee",
    status: "cleared",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    invoiceNo: "INV-1001",
    suffix: "A",
    number: 1,
  },
  {
    _id: "rec_2",
    type: "income",
    category: "Sales",
    amount: 12500,
    date: "2024-01-05",
    method: "bank",
    company: "comp_2",
    particular: "Product Sale",
    status: "cleared",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    invoiceNo: "INV-1002",
  },
  {
    _id: "rec_3",
    type: "expense",
    category: "Rent",
    amount: 8500,
    date: "2024-01-01",
    method: "bank",
    particular: "Office Rent",
    status: "cleared",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "rec_4",
    type: "income",
    category: "Service",
    amount: 7800,
    date: "2024-01-08",
    method: "bank",
    company: "comp_4",
    particular: "Medical Services Payment",
    status: "cleared",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    invoiceNo: "INV-1003",
  },
  {
    _id: "rec_5",
    type: "expense",
    category: "Utilities",
    amount: 1200,
    date: "2024-01-05",
    method: "bank",
    particular: "DEWA Bill Payment",
    status: "cleared",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "rec_6",
    type: "income",
    category: "Sales",
    amount: 15000,
    date: "2024-01-10",
    method: "bank",
    company: "comp_6",
    particular: "Hotel Booking Commission",
    status: "pending",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    invoiceNo: "INV-1004",
  },
  {
    _id: "rec_7",
    type: "expense",
    category: "Payroll",
    amount: 125000,
    date: "2024-01-01",
    method: "bank",
    particular: "Monthly Salaries",
    status: "cleared",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "rec_8",
    type: "income",
    category: "Service",
    amount: 9500,
    date: "2024-01-12",
    method: "bank",
    company: "comp_7",
    particular: "Logistics Services",
    status: "cleared",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    invoiceNo: "INV-1005",
  },
  {
    _id: "rec_9",
    type: "expense",
    category: "Marketing",
    amount: 5500,
    date: "2024-01-08",
    method: "bank",
    particular: "Digital Marketing Campaign",
    status: "cleared",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "rec_10",
    type: "income",
    category: "Sales",
    amount: 22000,
    date: "2024-01-14",
    method: "bank",
    company: "comp_8",
    particular: "Engineering Project Payment",
    status: "cleared",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    invoiceNo: "INV-1006",
  },
  {
    _id: "rec_11",
    type: "expense",
    category: "Software",
    amount: 2200,
    date: "2024-01-02",
    method: "bank",
    particular: "Software Subscriptions",
    status: "cleared",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "rec_12",
    type: "income",
    category: "Service",
    amount: 18000,
    date: "2024-01-15",
    method: "bank",
    company: "comp_10",
    particular: "Auto Trading Commission",
    status: "pending",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    invoiceNo: "INV-1007",
  },
  {
    _id: "rec_13",
    type: "expense",
    category: "Travel",
    amount: 8200,
    date: "2024-01-08",
    method: "bank",
    particular: "Business Travel Expenses",
    status: "cleared",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "rec_14",
    type: "income",
    category: "Sales",
    amount: 45000,
    date: "2024-01-17",
    method: "bank",
    company: "comp_11",
    particular: "Real Estate Commission",
    status: "cleared",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    invoiceNo: "INV-1008",
  },
  {
    _id: "rec_15",
    type: "expense",
    category: "Legal",
    amount: 4500,
    date: "2024-01-09",
    method: "bank",
    particular: "Legal Consultation",
    status: "cleared",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "rec_16",
    type: "income",
    category: "Service",
    amount: 13500,
    date: "2024-01-18",
    method: "cash",
    company: "comp_13",
    particular: "Education Services",
    status: "cleared",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    invoiceNo: "INV-1009",
  },
  {
    _id: "rec_17",
    type: "expense",
    category: "Maintenance",
    amount: 1800,
    date: "2024-01-05",
    method: "cash",
    particular: "Equipment Servicing",
    status: "cleared",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "rec_18",
    type: "income",
    category: "Sales",
    amount: 28000,
    date: "2024-01-20",
    method: "bank",
    company: "comp_14",
    particular: "IT Solutions Project",
    status: "pending",
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    invoiceNo: "INV-1010",
  },
];

export const generateInvoices = (): IInvoice[] => [
  {
    _id: "inv_1",
    invoiceNo: 1001,
    company: "comp_1",
    amount: 5250,
    tax: 250,
    status: "sent",
    date: "2024-01-01",
    title: "Consulting Services",
    suffix: "A",
    location: "Dubai",
    trn: "100200300",
    purpose: "Visa Processing",
    items: [
      {
        title: "Service Charge",
        desc: "Professional fees",
        rate: 5000,
        quantity: 1,
      },
    ],
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "inv_2",
    invoiceNo: 1002,
    company: "comp_2",
    amount: 12500,
    status: "paid",
    date: "2024-01-05",
    title: "Product Sales",
    location: "Abu Dhabi",
    items: [{ title: "Product A", desc: "Batch 1", rate: 12500, quantity: 1 }],
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "inv_3",
    invoiceNo: 1003,
    company: "comp_4",
    amount: 8190,
    tax: 390,
    status: "paid",
    date: "2024-01-08",
    title: "Healthcare Services",
    location: "Sharjah",
    trn: "100200301",
    purpose: "Medical Consultation",
    items: [
      {
        title: "Consultation Fee",
        desc: "General checkup",
        rate: 7800,
        quantity: 1,
      },
    ],
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "inv_4",
    invoiceNo: 1004,
    company: "comp_6",
    amount: 15750,
    tax: 750,
    status: "sent",
    date: "2024-01-10",
    title: "Hotel Booking Services",
    suffix: "B",
    location: "Abu Dhabi",
    trn: "100200302",
    purpose: "Business Event",
    items: [
      {
        title: "Booking Commission",
        desc: "Hotel reservations",
        rate: 15000,
        quantity: 1,
      },
    ],
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "inv_5",
    invoiceNo: 1005,
    company: "comp_7",
    amount: 9975,
    tax: 475,
    status: "paid",
    date: "2024-01-12",
    title: "Logistics Services",
    location: "Dubai",
    trn: "100200303",
    purpose: "Freight Management",
    items: [
      {
        title: "Transportation Fee",
        desc: "Container shipping",
        rate: 9500,
        quantity: 1,
      },
    ],
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "inv_6",
    invoiceNo: 1006,
    company: "comp_8",
    amount: 23100,
    tax: 1100,
    status: "paid",
    date: "2024-01-14",
    title: "Engineering Services",
    suffix: "C",
    location: "Ajman",
    trn: "100200304",
    purpose: "Project Development",
    items: [
      {
        title: "Engineering Consultation",
        desc: "Building design",
        rate: 22000,
        quantity: 1,
      },
    ],
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "inv_7",
    invoiceNo: 1007,
    company: "comp_10",
    amount: 18900,
    tax: 900,
    status: "sent",
    date: "2024-01-15",
    title: "Auto Trading Services",
    location: "Dubai",
    trn: "100200305",
    purpose: "Vehicle Purchase",
    items: [
      {
        title: "Commission Fee",
        desc: "Car sale commission",
        rate: 18000,
        quantity: 1,
      },
    ],
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "inv_8",
    invoiceNo: 1008,
    company: "comp_11",
    amount: 47250,
    tax: 2250,
    status: "paid",
    date: "2024-01-17",
    title: "Real Estate Commission",
    suffix: "A",
    location: "Abu Dhabi",
    trn: "100200306",
    purpose: "Property Sale",
    items: [
      {
        title: "Broker Fee",
        desc: "Villa sale commission",
        rate: 45000,
        quantity: 1,
      },
    ],
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "inv_9",
    invoiceNo: 1009,
    company: "comp_13",
    amount: 14175,
    tax: 675,
    status: "paid",
    date: "2024-01-18",
    title: "Education Services",
    location: "Dubai",
    trn: "100200307",
    purpose: "Training Courses",
    items: [
      {
        title: "Course Fee",
        desc: "Professional certification",
        rate: 13500,
        quantity: 1,
      },
    ],
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "inv_10",
    invoiceNo: 1010,
    company: "comp_14",
    amount: 29400,
    tax: 1400,
    status: "sent",
    date: "2024-01-20",
    title: "IT Solutions Package",
    suffix: "D",
    location: "Dubai",
    trn: "100200308",
    purpose: "Software Development",
    items: [
      {
        title: "Development Fee",
        desc: "Custom software",
        rate: 28000,
        quantity: 1,
      },
    ],
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "inv_11",
    invoiceNo: 1011,
    company: "comp_3",
    amount: 16800,
    tax: 800,
    status: "paid",
    date: "2024-01-22",
    title: "Trading Services",
    location: "Dubai",
    trn: "100200309",
    purpose: "Import/Export",
    items: [
      {
        title: "Trading Fee",
        desc: "Import facilitation",
        rate: 16000,
        quantity: 1,
      },
    ],
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "inv_12",
    invoiceNo: 1012,
    company: "comp_5",
    amount: 11550,
    tax: 550,
    status: "sent",
    date: "2024-01-23",
    title: "Digital Marketing Campaign",
    suffix: "E",
    location: "Dubai",
    trn: "100200310",
    purpose: "Brand Promotion",
    items: [
      {
        title: "Marketing Services",
        desc: "Social media campaign",
        rate: 11000,
        quantity: 1,
      },
    ],
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "inv_13",
    invoiceNo: 1013,
    company: "comp_12",
    amount: 32550,
    tax: 1550,
    status: "paid",
    date: "2024-01-24",
    title: "Food Production Services",
    location: "Sharjah",
    trn: "100200311",
    purpose: "Catering Supply",
    items: [
      {
        title: "Production Fee",
        desc: "Bulk food production",
        rate: 31000,
        quantity: 1,
      },
    ],
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "inv_14",
    invoiceNo: 1014,
    company: "comp_15",
    amount: 24150,
    tax: 1150,
    status: "sent",
    date: "2024-01-25",
    title: "Textile Trading",
    suffix: "F",
    location: "Sharjah",
    trn: "100200312",
    purpose: "Fabric Supply",
    items: [
      {
        title: "Wholesale Fee",
        desc: "Textile materials",
        rate: 23000,
        quantity: 1,
      },
    ],
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "inv_15",
    invoiceNo: 1015,
    company: "comp_16",
    amount: 21000,
    tax: 1000,
    status: "paid",
    date: "2024-01-26",
    title: "Property Management Services",
    location: "Abu Dhabi",
    trn: "100200313",
    purpose: "Building Maintenance",
    items: [
      {
        title: "Management Fee",
        desc: "Monthly property management",
        rate: 20000,
        quantity: 1,
      },
    ],
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "inv_16",
    invoiceNo: 1016,
    company: "comp_17",
    amount: 19950,
    tax: 950,
    status: "sent",
    date: "2024-01-27",
    title: "Event & Catering Services",
    suffix: "G",
    location: "Dubai",
    trn: "100200314",
    purpose: "Corporate Event",
    items: [
      {
        title: "Catering Package",
        desc: "Full event service",
        rate: 19000,
        quantity: 1,
      },
    ],
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const generateUserActivities = (): IUserActivity[] => [
  {
    _id: "act_1",
    targetUser: "user_2",
    performedBy: "user_1",
    action: "create",
    details: "Created user account",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
  {
    _id: "act_2",
    targetUser: "user_2",
    performedBy: "user_1",
    action: "role_change",
    details: "Promoted to Manager",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
  {
    _id: "act_3",
    targetUser: "user_3",
    performedBy: "user_1",
    action: "create",
    details: "Created user account",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
  {
    _id: "act_4",
    targetUser: "user_4",
    performedBy: "user_1",
    action: "create",
    details: "Created partner account",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
  {
    _id: "act_5",
    targetUser: "user_5",
    performedBy: "user_4",
    action: "create",
    details: "Created employee account",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
  {
    _id: "act_6",
    targetUser: "user_6",
    performedBy: "user_1",
    action: "status_change",
    details: "Deactivated user account",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
  {
    _id: "act_7",
    targetUser: "user_7",
    performedBy: "user_1",
    action: "create",
    details: "Created partner account",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
  {
    _id: "act_8",
    targetUser: "user_8",
    performedBy: "user_7",
    action: "create",
    details: "Created employee account",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
  {
    _id: "act_9",
    targetUser: "user_9",
    performedBy: "user_1",
    action: "create",
    details: "Created employee account",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
  {
    _id: "act_10",
    targetUser: "user_10",
    performedBy: "user_4",
    action: "create",
    details: "Created employee account",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
  {
    _id: "act_11",
    targetUser: "user_11",
    performedBy: "user_1",
    action: "create",
    details: "Created partner account",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
  {
    _id: "act_12",
    targetUser: "user_12",
    performedBy: "user_11",
    action: "create",
    details: "Created employee account",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
  {
    _id: "act_13",
    targetUser: "user_13",
    performedBy: "user_1",
    action: "status_change",
    details: "Deactivated user account",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
  {
    _id: "act_14",
    targetUser: "user_14",
    performedBy: "user_7",
    action: "create",
    details: "Created employee account",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
  {
    _id: "act_15",
    targetUser: "user_15",
    performedBy: "user_1",
    action: "create",
    details: "Created partner account",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
  {
    _id: "act_16",
    targetUser: "user_3",
    performedBy: "user_1",
    action: "role_change",
    details: "Updated role to Senior Employee",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
  {
    _id: "act_17",
    targetUser: "user_8",
    performedBy: "user_7",
    action: "role_change",
    details: "Promoted to Team Lead",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    published: true,
  },
];
