export const DOCUMENT_CATEGORY_OPTIONS = [
  "renewal police",
  "renewal estelam",
  "trade license",
  "establishment card",
  "moa",
  "immigration",
  "vat",
  "tenancy contract",
  "passport",
  "eid",
  "visa",
  "labor card",
  "other",
  "renewal شرطة",
  "renewal استلام",
  "استمارة",
  "تعديل",
  "تفويض",
];

export const CREDENTIAL_CATEGORY_OPTIONS = [
  "immigration",
  "labor",
  "mohre",
  "gdrfa",
  "tasheel",
  "vat",
  "uae pass",
  "other",
  "emigration الجوازات",
  "labor العمل",
  "mohre",
  "icp",
  "شرطة",
];
