export const PERMISSION_GROUPS: Record<string, string[]> = {
  security: [
    "admin.access",
    "settings.read",
    "settings.write",
    "roles.manage",
    "settings.manage.roles",
    "settings.manage.permissions",
  ],
  settings: [
    "settings.manage.document-types",
    "settings.manage.credential-platforms",
    "settings.manage.office-categories",
    "settings.manage.payment-methods",
    "settings.manage.payment-statuses",
    "settings.manage.particular-suggestions",
  ],
  users: [
    "users.read",
    "users.create",
    "users.update",
    "users.delete",
    "users.reactivate",
  ],
  audit: [
    "users.activity.read",
  ],
  dashboard: [
    "dashboard.view.business-pulse",
  ],
  entities: [
    "entities.read",
    "entities.write",
  ],
  documents: [
    "documents.read",
    "documents.write",
  ],
  invoices: [
    "payments.view.invoices",
    "payments.create.invoices",
    "payments.update.invoices",
    "payments.delete.invoices",
  ],
  payments: [
    "payments.admin",
    "payments.read",
    "payments.write",
    "payments.view.transactions",
    "payments.view.records-summary",
    "payments.view.office-records",
    "payments.view.self-transfers",
    "payments.view.liability-records",
    "payments.view.credit-debit-lists",
    "payments.view.monthly-stats",
    "payments.view.finance-summary-page",
    "payments.view.reports",
    "payments.view.finance",
    "payments.create.transactions",
    "payments.update.transactions",
    "payments.delete.transactions",
    "payments.manage.self-transfers",
    "payments.manage.recompute-monthly-stats",
    "payments.manage.particular-suggestions",
  ],
  tasks: [
    "tasks.read",
    "tasks.manage",
    "tasks.view.my",
    "tasks.view.all",
    "tasks.view.detail",
    "tasks.create",
    "tasks.assign",
    "tasks.update",
    "tasks.delete",
    "tasks.export",
    "tasks.calendar.view",
    "tasks.links.suggest",
    "tasks.complete",
    "tasks.notifications.read",
  ],
};

export const ALL_PERMISSIONS = Array.from(
  new Set(Object.values(PERMISSION_GROUPS).flat()),
);
